name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install nightly
        run: rustup install nightly
    
      - name: Add targets
        run: rustup target add thumbv7em-none-eabihf
  
      - name: Install flip-link
        run: cd / && cargo install flip-link
    
      - name: Build
        run: cargo +nightly build  --target=thumbv7em-none-eabihf --verbose

